
export const TYPES = {
  IEventRepository: Symbol.for('IEventRepository'),
  ITicketRepository: Symbol.for('ITicketRepository'),
  IUserRepository: Symbol.for('IUserRepository'),
  CreateEventUseCase: Symbol.for('CreateEventUseCase'),
  GetEventsUseCase: Symbol.for('GetEventsUseCase'),
  UpdateEventUseCase: Symbol.for('UpdateEventUseCase'),
  DeleteEventUseCase: Symbol.for('DeleteEventUseCase'),
  CreateCheckoutSessionUseCase: Symbol.for('CreateCheckoutSessionUseCase'),
  HandleStripeWebhookUseCase: Symbol.for('HandleStripeWebhookUseCase'),
  BookTicketUseCase: Symbol.for('BookTicketUseCase'),
  GetTicketsByUserUseCase: Symbol.for('GetTicketsByUserUseCase'),
  VerifyTicketUseCase: Symbol.for('VerifyTicketUseCase'),
  GetLatestTicketUseCase: Symbol.for('GetLatestTicketUseCase'),
  TicketUseCase: Symbol.for('TicketUseCase'),
  GetAllTicketsUseCase: Symbol.for('GetAllTicketsUseCase'),
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  LoginUserUseCase: Symbol.for('LoginUserUseCase'),
  GoogleAuthUseCase: Symbol.for('GoogleAuthUseCase'),
  VerifyOtpUseCase: Symbol.for('VerifyOtpUseCase'),
  ResendOtpUseCase: Symbol.for('ResendOtpUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  GetAllUsersUseCase: Symbol.for('GetAllUsersUseCase'),
  ToggleUserStatusUseCase: Symbol.for('ToggleUserStatusUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  GetUserByIdUseCase: Symbol.for('GetUserByIdUseCase'),
  EventController: Symbol.for('EventController'),
  TicketController: Symbol.for('TicketController'),
  UserController: Symbol.for('UserController'),
};